services:

  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: lms_info
    volumes:
      - "./lms_info.sql:/docker-entrypoint-initdb.d/lms_info.sql"
    ports: 
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    depends_on:
      - mysqldb

  course-companion-app:
    build: .
    container_name: course-companion-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: lms_info
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysqldb
